### ISSUE TITLE
Translation Progress

### ISSUE THREAD

**Issue by NSMau** [NSMau/swiftbook-es#3]
# 🚨 Please Read this before contributing 🚨

This issue will serve as a means to track the progress of the translation of the book. I intend to keep the translation organized and in sync with all contributors. Please verify that the document you would like to translate hasn't been claimed by someone else.

## Maintainers List

- @patternina 

## For New Translators

To translate a page:

Check that no one else has claimed your page in the checklist and comments below. Do not create new issues claiming new work please, let's keep everything here. If you already have an issue opened, please close it after your PR gets merged 🎉. Thanks!

Comment below with the name of the page you would like to translate. Take only one page at a time.
Submit a PR, assign it to @patternina,  and add a link to it to your comment!

Please check the style guide to make sure translations are written in a consistent manner.

## Status Indicators

* ✍🏽 – Translation In Progress
* 👀 – Under Review
* 🎉 – Done

### Language Guide
- [x] ~~The Basics~~ (@patternina) 🎉
- [x] ~~Basic Operators~~ (@patternina) 🎉
- [x] ~~Strings and Characters~~ (@patternina) 🎉
- [ ] Collection Types (@patternina) ✍🏽
- [ ] Control Flow (@patternina) ✍🏽
- [x] ~~Functions~~ (@patternina) 🎉
- [x] ~~Closures~~ (@patternina) 🎉
- [ ] Enumerations
- [ ] Structures and Classes (@CacereLucas) 👀
- [ ] Properties (@Kiszaner) ✍🏽
- [x] ~~Methods~~ (@oscar-moreno) 🎉
- [ ] Subscripts
- [x] ~~Inheritance~~ (@patternina) 🎉
- [ ] Initialization
- [ ] Deinitialization
- [ ] Optional Chaining
- [ ] Error Handling (@MarioHdezC) ✍🏽
- [ ] Concurrency
- [ ] Type Casting
- [ ] Nested Types (@fjrois) ✍🏽
- [ ] Extensions
- [ ] Protocols
- [ ] Generics (@pitt500) ✍🏽
- [ ] Opaque Types
- [ ] Automatic Reference Counting (@bigimot22) ✍🏽
- [ ] Memory Safety
- [ ] Access Control
- [ ] Advanced Operators

### Language Reference

- [ ] About the Language Reference (@patternina) ✍🏽
- [ ] Lexical Structure
- [ ] Types
- [ ] Expressions
- [ ] Statements
- [ ] Declarations
- [ ] Attributes
- [ ] Patterns
- [ ] Generic Parameters and Arguments
- [ ] Summary of the Grammar

### Revision History
- [ ] Document Revision History

**Comment by pitt500** [comment]
Hola que tal @spaceinvadev! Primero que nada, muchas gracias por comenzar esta iniciativa! ❤️ 
Me gustaría apoyarte traduciendo la pagina de Generics. Ya leí la documentación que dejaste. 
Quedo en espera de que la tarea sea asignada a mí en esta página.

Saludos,
Pitt

**Comment by tmsanchez** [comment]
Hi @spaceinvadev, I would like to collaborate translating Enumerations (Enumeraciones).

**Comment by pol-piella** [comment]
Hi @spaceinvadev, I would like to contribute by translating `Collection Types`.

**Comment by spaceinvadev** [comment]
Hi, Pedro (@pitt500). Thanks for contributing to the project. You can go ahead and work on translating the Generics article.

**Comment by tmsanchez** [comment]
Hi @spaceinvadev I'm done with **Enumerations** chapter, I would like to collaborate during this week with "**Functions**" chapter

**Comment by CacereLucas** [comment]
Hi @tmsanchez, I would like to collaborate translating `Structures and Classes`. Let me know what you think. 

Regards,
Lucas

**Comment by spaceinvadev** [comment]
Hi, @CacereLucas. Thanks for your interest in contributing to the project. You can go ahead and work on translating your requested article. 👍🏼

**Comment by Kiszaner** [comment]
Hi @spaceinvadev, I would like to contribute to the translating effort taking `Properties`.

**Comment by patternina** [comment]
> Hello, @Kiszaner. Thank you for your interest in contributing to this project. You can go ahead and translate the article of your choice. 👍🏼

**Comment by oscar-moreno** [comment]
Hello @spaceinvadev, thanks for start this project 🙂. I would like to contribute translating the page `Methods`.

Kind regards.

**Comment by mprcodes** [comment]
Saludos, @oscar-moreno. Muchas gracias por tu colaboración y apoyo al proyecto. Desde luego que puedes ir trabajando en la traducción del artículo mencionado.

Muchas gracias.

**Comment by mprcodes** [comment]
Saludos, @pol-piella, @tmsanchez, @CacereLucas, y @pitt500.

¿Podría, por favor, confirmar si aún están interesados en contribuir traduciendo los artículos solicitados? Ha pasado cierto tiempo ya, y sería preferible, liberar los artículos para que futuros interesados los tome y contribuyan al proyecto.

**Comment by pitt500** [comment]
> Saludos, @pol-piella, @tmsanchez, @CacereLucas, y @pitt500.
> 
> ¿Podrían, por favor, confirmar si aún están interesados en contribuir traduciendo los artículos solicitados? Ha pasado cierto tiempo ya y sería preferible liberar los artículos para que futuros interesados los tomen y contribuyan al proyecto.

Hola @mprcodes, te pido una disculpa por la demora. Llevaba como 2/3 de la traducción (de Generics), pero tuve que mudarme a USA y lo fui postergando (long story). Podría comprometerme a retomarlo y tener lista la parte restante para el 31 de Enero a más tardar. Si te parece bien, solo confirmame. 

Saludos,
Pitt

**Comment by mprcodes** [comment]
Hola, @pitt500. Gracias por el update. No hay problema, entiendo que todos tiene sus prioridades. Puedes seguir trabajando en tu aporte. Feliz día.

**Comment by CacereLucas** [comment]
> Saludos, @pol-piella, @tmsanchez, @CacereLucas, y @pitt500.
> 
> 
> 
> ¿Podrían, por favor, confirmar si aún están interesados en contribuir traduciendo los artículos solicitados? Ha pasado cierto tiempo ya y sería preferible liberar los artículos para que futuros interesados los tomen y contribuyan al proyecto.

Saludos! Tengo la traducción a un 75%. Disculpa por la demora, lo tendré a la mayor brevedad posible.

**Comment by pol-piella** [comment]
> Saludos, @pol-piella, @tmsanchez, @CacereLucas, y @pitt500.
> 
> ¿Podrían, por favor, confirmar si aún están interesados en contribuir traduciendo los artículos solicitados? Ha pasado cierto tiempo ya y sería preferible liberar los artículos para que futuros interesados los tomen y contribuyan al proyecto.

Hola! 

Perdona, no he tenido tiempo de traducirlo 😔 Si quieres puedes liberarlo y cuando tenga tiempo otra vez me asignaré otra parte para traducir. 

Disculpa por las molestias.

**Comment by MarioHdezC** [comment]
Hi @mprcodes! I would like to contribute translating the page `Error Handling`.

Regards.

**Comment by mprcodes** [comment]
> Hi @mprcodes! I would like to contribute translating the page `Error Handling`.
> 
> Regards.

Hey, @MarioHdezC. Thanks for your interest in contributing to the project. Feel free to fork the repo and start working on your requested article. Have a nice day!

**Comment by bigimot22** [comment]
Hola @mprcodes, I'd like to translate **Automatic Reference Counting**

**Comment by mprcodes** [comment]
> Hola @mprcodes, I'd like to translate **Automatic Reference Counting**

Hello, @bigimot22. Sure you can! Thanks for your collaboration on the project! Happy translation!

**Comment by KrlitosForever** [comment]
Hola quiero ayurdar a traducir ** Enumerations**
Quedo atento saludos desde 🇨🇱

**Comment by trsplms** [comment]
> Hola quiero ayurdar a traducir **Enumerations** Quedo atento saludos desde 🇨🇱

Hola, Carlos. Gracias por tu interés en colaborar con el proyecto. Claro, puedes trabajar en esa traducción.

**Comment by KrlitosForever** [comment]
> > Hola quiero ayurdar a traducir **Enumerations** Quedo atento saludos desde chile
> 
> Hola, Carlos. Gracias por tu interés en colaborar con el proyecto. Claro, puedes trabajar en esa traducción.

Consulta me sale el siguiente error:
![image](https://user-images.githubusercontent.com/7423579/236711451-9e6b2a0b-08c3-4066-b05b-dda976d525ee.png)

**Comment by KrlitosForever** [comment]
> > > Hola quiero ayurdar a traducir **Enumerations** Quedo atento saludos desde chile
> > 
> > 
> > Hola, Carlos. Gracias por tu interés en colaborar con el proyecto. Claro, puedes trabajar en esa traducción.
> 
> Consulta me sale el siguiente error: ![image](https://user-images.githubusercontent.com/7423579/236711451-9e6b2a0b-08c3-4066-b05b-dda976d525ee.png)

Enumerations creo que esta asignada a [tmsanchez](https://github.com/tmsanchez) Creo que debería elegir otro artículo.

**Comment by trsplms** [comment]
> Enumerations creo que esta asignada a @tmsanchez Creo que debería elegir otro artículo. Incluso creo que tiene un PR.
> 
> 
> 
> @trsplms quiero que me asignes **Subscripts** 

Yo a él le solicité algunos cambios a su PR, pero eso ya fue hace más de un año, así que supongo que no sigue interesado en colaborar. Puedes tomar ese o el que acabas de solicitar, como lo prefieras.

**Comment by KrlitosForever** [comment]
> > Enumerations creo que esta asignada a @tmsanchez Creo que debería elegir otro artículo. Incluso creo que tiene un PR.
> > @trsplms quiero que me asignes **Subscripts**
> 
> Yo a él le solicité algunos cambios a su PR, pero eso ya fue hace más de un año, así que supongo que no sigue interesado en colaborar. Puedes tomar ese o el que acabas de solicitar, como lo prefieras.

Perfecto iniciaré **Subscripts** saludos.

**Comment by fjrois** [comment]
Hola @patternina! Gracias por liderar este proyecto.

Me gustaría colaborar traduciendo la sección **Nested Types**.

**Comment by patternina** [comment]
> Hola @patternina! Gracias por liderar este proyecto.
> 
> Me gustaría colaborar traduciendo la sección **Nested Types**.

Saludos, @fjrois. Gracias por tu interés en colaborar con el proyecto. Y, claro, puedes traducir el artículo solicitado.

**Comment by fjrois** [comment]
> > Hola @patternina! Gracias por liderar este proyecto.
> > Me gustaría colaborar traduciendo la sección **Nested Types**.
> 
> Saludos, @fjrois. Gracias por tu interés en colaborar con el proyecto. Y, claro, puedes traducir el artículo solicitado.

@patternina Parece que no tengo permisos para añadir etiquetas, pero aquí está mi PR, `Ready for review`: https://github.com/patternina/swift-book-es/pull/35

**Comment by fjrois** [comment]
@patternina Me gustaría traducir la sección **Deinitialization**.

**Comment by fjrois** [comment]
> @patternina Me gustaría traducir la sección **Deinitialization**.

@patternina Aquí está la PR para `Deinitialization`: https://github.com/patternina/swiftbook-es/pull/37

Me gustaría continuar, traduciendo la sección `Initialization`. Por favor, confirma y asígnamela cuando puedas. Gracias.

**Comment by kontroldev** [comment]
> Saludos, @pol-piella, @tmsanchez, @CacereLucas, y @pitt500.
> 
> 
> 
> ¿Podrían, por favor, confirmar si aún están interesados en contribuir traduciendo los artículos solicitados? Ha pasado cierto tiempo ya y sería preferible liberar los artículos para que futuros interesados los tomen y contribuyan al proyecto.

Yo estaría dispuesto a ayudar a seguir traduciendo la documentación.
Saludos.

**Comment by patternina** [comment]
Gracias, @fjrois y @kontroldev. Les agradecería me dieran un par de semanas para continuar con la traducción de artículos, puesto que he decidido migrar el proyecto para que sea una copia exacta de la implementación actual de Apple y Swift.org. Para ello he clonado el repo a [patternina/swift-book-es](https://github.com/patternina/swiift-book-es). En el siguiente link pueden apreciar un preview de cómo sería la nueva implementación: https://patternina.github.io/swift-book-es/documentation/the-swift-programming-language

El tiempo lo necesito para migrar el contenido traducido hasta ahora y para estructurar y comunicar el flujo a seguir para los futuros aportes.

**Comment by neozeno** [comment]
Saludos @fjrois, @kontroldev, @KrlitosForever, @bigimot22, @MarioHdezC.

Una vez que Swift.org ha decidido llevar la documentación a open-source, he decidido migrar este proyecto al repositorio [NSMau/swift-book-es](https://github.com/NSMau/swift-book-es) para así poder realizar una copia exacta de la documentación oficial, y simplemente traducir el contenido. La nueva versión de la traducción al español está disponible en [swiftbook.es](https://swiftbook.es/documentation/the-swift-programming-language/) y ya está disponible para colaborar con las traducciones.

<img width="1680" alt="Screenshot 2023-09-22 at 5 06 40 PM" src="https://github.com/NSMau/swiftbook-es/assets/49292621/a954bfc0-3eee-4fca-ac98-688f1149c831">


Por consiguiente, este repositorio pasará a ser archivado.
